[project]
name = "ai-productivity-enforcer"
version = "0.2.0"
description = "Persistent MCP servers for productivity, learning, and personalized assistance."
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "mcp[cli]>=1.11.0",
]
